### PR TITLE
Set App Icon Badge Number on iOS

### LINKED ISSUE #247: Set Application Icon Badge Number
Need implementation for setting app icon badge number
image

### PR DESCRIPTION
**Pull request by javasuns**
Implementation for setting the application icon badge number

Fixes #247

### CODE REVIEW

**Comment by jperedadnr** [comment]
This PR is about the app icon badge, so there shouldn't be other non-related changes.
The new StoreReviewService module should go in a different issue/PR.

**Comment by abhinayagarwal** [comment]
Hi @javasuns 

Can you updte the PR as per review from @jperedadnr ?

**Comment by javasuns** [comment]
> Hi @javasuns
> 
> Can you updte the PR as per review from @jperedadnr ?

Hello there and sorry for the late reply. I am currently without a mac device as there have been a fault with my latest macbook and i am in the waiting process for the new line of macbook pros to be released before proceeding with a new purchase. Sorry for not being able to do this change, as The code in this PR should have been an isolated change and not dependant on any other change.

**Comment by websystemtechnology** [comment]
Why the change of icone badge does't merge into main pr?

**Comment by websystemtechnology** [comment]
Why the change of icone badge does't merge into main pr?

**Pull request closed without merging**
